//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Workspaces {
    
    private WorkspacesWorkspace[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Workspace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WorkspacesWorkspace[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WorkspacesWorkspace {
    
    private string commentField;
    
    private string lastAccessDateField;
    
    private WorkspacesWorkspaceFoldersWorkingFolder[][] foldersField;
    
    private WorkspacesWorkspaceOwnerAliasesString[][] ownerAliasesField;
    
    private string computerField;
    
    private string islocalField;
    
    private string nameField;
    
    private string ownerdispField;
    
    private string owneridField;
    
    private string ownertypeField;
    
    private string ownerField;
    
    private string owneruniqField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastAccessDate {
        get {
            return this.lastAccessDateField;
        }
        set {
            this.lastAccessDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkingFolder", typeof(WorkspacesWorkspaceFoldersWorkingFolder[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public WorkspacesWorkspaceFoldersWorkingFolder[][] Folders {
        get {
            return this.foldersField;
        }
        set {
            this.foldersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("string", typeof(WorkspacesWorkspaceOwnerAliasesString[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WorkspacesWorkspaceOwnerAliasesString[][] OwnerAliases {
        get {
            return this.ownerAliasesField;
        }
        set {
            this.ownerAliasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string computer {
        get {
            return this.computerField;
        }
        set {
            this.computerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string islocal {
        get {
            return this.islocalField;
        }
        set {
            this.islocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ownerdisp {
        get {
            return this.ownerdispField;
        }
        set {
            this.ownerdispField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ownerid {
        get {
            return this.owneridField;
        }
        set {
            this.owneridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ownertype {
        get {
            return this.ownertypeField;
        }
        set {
            this.ownertypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string owneruniq {
        get {
            return this.owneruniqField;
        }
        set {
            this.owneruniqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WorkspacesWorkspaceFoldersWorkingFolder {
    
    private string localField;
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string local {
        get {
            return this.localField;
        }
        set {
            this.localField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WorkspacesWorkspaceOwnerAliasesString {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
